cc_binary(
    name = "wimbledon_2019",
    srcs = ["wimbledon_2019.c"],
    deps = [
        "//tennisfanclub/fan:behavior",
        "@television//television/control",
        "@television//television/channel:list",
    ],
)
